### ISSUE TITLE
DotDevelop Icon idea

### ISSUE THREAD

**Issue by trampster** [dotdevelop/community#4]
DotDevelop will need it's own Icon.

I'm not graphic designer, but I've had a go at creating an icon for DotDevelop. 

I've created an svg using inkscape: and exported at various sizes.

The design has two D's mirrored and a Dot in the center.

![DotDevelop32](https://user-images.githubusercontent.com/2063633/80277595-341c0980-8744-11ea-9c1b-199f17fbf1e7.png)
![DotDevelop64](https://user-images.githubusercontent.com/2063633/80277597-354d3680-8744-11ea-9bc8-44fbecb8289c.png)
![DotDevelop128](https://user-images.githubusercontent.com/2063633/80277598-354d3680-8744-11ea-9b57-e361dfa4e16c.png)
![DotDevelop256](https://user-images.githubusercontent.com/2063633/80277599-35e5cd00-8744-11ea-81a8-6559f9a86664.png)

I don't mind if you use it or not, might be better to get a real graphic designer to make one.

**Comment by lytico** [comment]
please, submit your svg-file to:
https://github.com/dotdevelop/community/tree/master/logo
thanks!

**Comment by knuxbbs** [comment]
Addressed by #7.
