### ISSUE TITLE
[General]

### ISSUE THREAD

**Issue by scherenhaenden** [dotdevelop/community#5]
First, I'd like to give a big thanks to the persone that created this fork and of course for anyone that can help.

Things I think we might need to may this happen, work and success.
1.- We should have at list a plan, even if little. We need to have an idea of what we problems are we facing, have to split those problem into pieces and how to implementate them. This plan needs to be clear as cristal. The clearer the better.
2.- Once we have clarified that, we might need some media channels, meaning, maybe a website that is not the same as the monodevelop.com (I could help on that, I not designer but I'm a good developer.). We might need at least one Chat channel to speak about the issues that are in our concern and for the sake of the project. 
3.- Update documentation (Readme, Code of conduct and other things).
4.- Maybe a strategy of how to involve ppl in this project. 

I just wanted to begin we this few things.... there is a lot more behind the first mountain, but maybe is there someone else thinking about these things. From myself I can say that I would try to help as much as it gets, but this corona situation hit me hard and I have to be dealing with many issues for the next months... ofc I can be there for testing and giving a hand wherever is possible for me to do it.

And thanks again guys!

**Comment by lytico** [comment]
First draft for roadmap

see: https://github.com/dotdevelop/community/blob/master/roadmap.md

**Comment by lytico** [comment]
website-dummy is here:
https://github.com/dotdevelop/dotdevelop.github.io

**Comment by harry-cpp** [comment]
You guys definitely need a Discord or a Gitter for discussions.
