### ISSUE TITLE
Discord or Gitter for discussions

### ISSUE THREAD

**Issue by lytico** [dotdevelop/community#8]
https://discordapp.com/open-source :

https://discord.com/channels/704812455863517334/704812455863517337

**Comment by knuxbbs** [comment]
I vote for maintain the old MonoDevelop room in Gitter. We will avoid further fragmenting the community.

Also, I've created a Discord channel: https://discord.gg/FeaquS

Gitter makes easy for any Github user to join the conversation, and Discord has nice features.

**Comment by trampster** [comment]
If we intend to use the MonoDevelop Gitter room, then we really should seek their permission to do so.

The discord looks nice.

**Comment by harry-cpp** [comment]
Discord. Do not use the old gitter room.

**Comment by lytico** [comment]
@knocte wrote: "I disagree about switching to Discord"

**Comment by lextm** [comment]
Which channel to use really depends on the goals of this initiative.

If the key goal is to fork and move away from the original MonoDevelop repo, then a separate channel makes sense.

However, if the key goal is to fork, prepare the Linux/Windows port, and merge back to the original repo, I don't think a separate channel is needed. I think everyone cares or cared about MonoDevelop are already in the Gitter room, so sharing information there is critical to keep everyone engaged (even if most of the guys won't contribute to this fork).

I am against moving too far away from the original repo. Microsoft/Xamarin so far is slowly releasing more and more code from VS for Mac, and the overall architecture of MonoDevelop remains. So any new work in this fork should be able to be sent back. I assume this fork only gives the community a test field to focus on Linux/Windows specific issues, which Microsoft/Xamarin is reluctant to work on. I might be wrong though.

**Comment by lytico** [comment]
> Microsoft/Xamarin so far is slowly releasing more and more code from VS for Mac
only to  make possible writing extensions for VS (mac or windows)

as far as i know now, they don't have any efforts or plans to open source an ide.

the whole vs-editor-api can be a trap. we'll work years on it to get it run over gkt and then it turns out that critical parts are (and will be) closed source.

**Comment by harry-cpp** [comment]
Check the discord everyone.

**Comment by thassin** [comment]
The discord invite link above is no longer working. Any advice how to reach the channel?

**Comment by knuxbbs** [comment]
@thassin Try with this link: https://discord.gg/dBfyyHX
